; Auto-generated. Do not edit!


(cl:in-package lab_2-msg)


;//! \htmlinclude actionResult.msg.html

(cl:defclass <actionResult> (roslisp-msg-protocol:ros-message)
  ((response
    :reader response
    :initarg :response
    :type cl:integer
    :initform 0))
)

(cl:defclass actionResult (<actionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <actionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'actionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lab_2-msg:<actionResult> is deprecated: use lab_2-msg:actionResult instead.")))

(cl:ensure-generic-function 'response-val :lambda-list '(m))
(cl:defmethod response-val ((m <actionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lab_2-msg:response-val is deprecated.  Use lab_2-msg:response instead.")
  (response m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <actionResult>) ostream)
  "Serializes a message object of type '<actionResult>"
  (cl:let* ((signed (cl:slot-value msg 'response)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <actionResult>) istream)
  "Deserializes a message object of type '<actionResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'response) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<actionResult>)))
  "Returns string type for a message object of type '<actionResult>"
  "lab_2/actionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'actionResult)))
  "Returns string type for a message object of type 'actionResult"
  "lab_2/actionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<actionResult>)))
  "Returns md5sum for a message object of type '<actionResult>"
  "4bf37bc717f68787645077428bea3751")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'actionResult)))
  "Returns md5sum for a message object of type 'actionResult"
  "4bf37bc717f68787645077428bea3751")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<actionResult>)))
  "Returns full string definition for message of type '<actionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 response~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'actionResult)))
  "Returns full string definition for message of type 'actionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 response~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <actionResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <actionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'actionResult
    (cl:cons ':response (response msg))
))
