; Auto-generated. Do not edit!


(cl:in-package lab_2-msg)


;//! \htmlinclude actionGoal.msg.html

(cl:defclass <actionGoal> (roslisp-msg-protocol:ros-message)
  ((request
    :reader request
    :initarg :request
    :type cl:integer
    :initform 0))
)

(cl:defclass actionGoal (<actionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <actionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'actionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lab_2-msg:<actionGoal> is deprecated: use lab_2-msg:actionGoal instead.")))

(cl:ensure-generic-function 'request-val :lambda-list '(m))
(cl:defmethod request-val ((m <actionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lab_2-msg:request-val is deprecated.  Use lab_2-msg:request instead.")
  (request m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <actionGoal>) ostream)
  "Serializes a message object of type '<actionGoal>"
  (cl:let* ((signed (cl:slot-value msg 'request)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <actionGoal>) istream)
  "Deserializes a message object of type '<actionGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'request) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<actionGoal>)))
  "Returns string type for a message object of type '<actionGoal>"
  "lab_2/actionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'actionGoal)))
  "Returns string type for a message object of type 'actionGoal"
  "lab_2/actionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<actionGoal>)))
  "Returns md5sum for a message object of type '<actionGoal>"
  "7b8b3e2da8be658e01dee48451dead03")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'actionGoal)))
  "Returns md5sum for a message object of type 'actionGoal"
  "7b8b3e2da8be658e01dee48451dead03")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<actionGoal>)))
  "Returns full string definition for message of type '<actionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 request~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'actionGoal)))
  "Returns full string definition for message of type 'actionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 request~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <actionGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <actionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'actionGoal
    (cl:cons ':request (request msg))
))
