// Auto-generated. Do not edit!

// (in-package lab_2.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class actionFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.feeddback = null;
    }
    else {
      if (initObj.hasOwnProperty('feeddback')) {
        this.feeddback = initObj.feeddback
      }
      else {
        this.feeddback = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type actionFeedback
    // Serialize message field [feeddback]
    bufferOffset = _serializer.int64(obj.feeddback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type actionFeedback
    let len;
    let data = new actionFeedback(null);
    // Deserialize message field [feeddback]
    data.feeddback = _deserializer.int64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'lab_2/actionFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '77e2688e9a23836b8b093bb09e37e8cb';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int64 feeddback
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new actionFeedback(null);
    if (msg.feeddback !== undefined) {
      resolved.feeddback = msg.feeddback;
    }
    else {
      resolved.feeddback = 0
    }

    return resolved;
    }
};

module.exports = actionFeedback;
