// Generated by gencpp from file lab_1/turtle_velocityResponse.msg
// DO NOT EDIT!


#ifndef LAB_1_MESSAGE_TURTLE_VELOCITYRESPONSE_H
#define LAB_1_MESSAGE_TURTLE_VELOCITYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab_1
{
template <class ContainerAllocator>
struct turtle_velocityResponse_
{
  typedef turtle_velocityResponse_<ContainerAllocator> Type;

  turtle_velocityResponse_()
    {
    }
  turtle_velocityResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::lab_1::turtle_velocityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab_1::turtle_velocityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct turtle_velocityResponse_

typedef ::lab_1::turtle_velocityResponse_<std::allocator<void> > turtle_velocityResponse;

typedef boost::shared_ptr< ::lab_1::turtle_velocityResponse > turtle_velocityResponsePtr;
typedef boost::shared_ptr< ::lab_1::turtle_velocityResponse const> turtle_velocityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab_1::turtle_velocityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab_1::turtle_velocityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace lab_1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab_1::turtle_velocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab_1::turtle_velocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_1::turtle_velocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_1::turtle_velocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_1::turtle_velocityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_1::turtle_velocityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab_1::turtle_velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::lab_1::turtle_velocityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::lab_1::turtle_velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab_1/turtle_velocityResponse";
  }

  static const char* value(const ::lab_1::turtle_velocityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab_1::turtle_velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::lab_1::turtle_velocityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab_1::turtle_velocityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct turtle_velocityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab_1::turtle_velocityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::lab_1::turtle_velocityResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LAB_1_MESSAGE_TURTLE_VELOCITYRESPONSE_H
