// Generated by gencpp from file lab_1/turtle_velocityRequest.msg
// DO NOT EDIT!


#ifndef LAB_1_MESSAGE_TURTLE_VELOCITYREQUEST_H
#define LAB_1_MESSAGE_TURTLE_VELOCITYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab_1
{
template <class ContainerAllocator>
struct turtle_velocityRequest_
{
  typedef turtle_velocityRequest_<ContainerAllocator> Type;

  turtle_velocityRequest_()
    : major(0.0)
    , minor(0.0)
    , omega(0.0)  {
    }
  turtle_velocityRequest_(const ContainerAllocator& _alloc)
    : major(0.0)
    , minor(0.0)
    , omega(0.0)  {
  (void)_alloc;
    }



   typedef double _major_type;
  _major_type major;

   typedef double _minor_type;
  _minor_type minor;

   typedef double _omega_type;
  _omega_type omega;





  typedef boost::shared_ptr< ::lab_1::turtle_velocityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab_1::turtle_velocityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct turtle_velocityRequest_

typedef ::lab_1::turtle_velocityRequest_<std::allocator<void> > turtle_velocityRequest;

typedef boost::shared_ptr< ::lab_1::turtle_velocityRequest > turtle_velocityRequestPtr;
typedef boost::shared_ptr< ::lab_1::turtle_velocityRequest const> turtle_velocityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab_1::turtle_velocityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab_1::turtle_velocityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab_1::turtle_velocityRequest_<ContainerAllocator1> & lhs, const ::lab_1::turtle_velocityRequest_<ContainerAllocator2> & rhs)
{
  return lhs.major == rhs.major &&
    lhs.minor == rhs.minor &&
    lhs.omega == rhs.omega;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab_1::turtle_velocityRequest_<ContainerAllocator1> & lhs, const ::lab_1::turtle_velocityRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab_1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab_1::turtle_velocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab_1::turtle_velocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_1::turtle_velocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_1::turtle_velocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_1::turtle_velocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_1::turtle_velocityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab_1::turtle_velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8dda380a8a55b18c7abd86610253a772";
  }

  static const char* value(const ::lab_1::turtle_velocityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8dda380a8a55b18cULL;
  static const uint64_t static_value2 = 0x7abd86610253a772ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab_1::turtle_velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab_1/turtle_velocityRequest";
  }

  static const char* value(const ::lab_1::turtle_velocityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab_1::turtle_velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 major\n"
"float64 minor\n"
"float64 omega\n"
;
  }

  static const char* value(const ::lab_1::turtle_velocityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab_1::turtle_velocityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.major);
      stream.next(m.minor);
      stream.next(m.omega);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct turtle_velocityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab_1::turtle_velocityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab_1::turtle_velocityRequest_<ContainerAllocator>& v)
  {
    s << indent << "major: ";
    Printer<double>::stream(s, indent + "  ", v.major);
    s << indent << "minor: ";
    Printer<double>::stream(s, indent + "  ", v.minor);
    s << indent << "omega: ";
    Printer<double>::stream(s, indent + "  ", v.omega);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB_1_MESSAGE_TURTLE_VELOCITYREQUEST_H
