// Generated by gencpp from file lab_2/actionGoal.msg
// DO NOT EDIT!


#ifndef LAB_2_MESSAGE_ACTIONGOAL_H
#define LAB_2_MESSAGE_ACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab_2
{
template <class ContainerAllocator>
struct actionGoal_
{
  typedef actionGoal_<ContainerAllocator> Type;

  actionGoal_()
    : request(0)  {
    }
  actionGoal_(const ContainerAllocator& _alloc)
    : request(0)  {
  (void)_alloc;
    }



   typedef int64_t _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::lab_2::actionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab_2::actionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct actionGoal_

typedef ::lab_2::actionGoal_<std::allocator<void> > actionGoal;

typedef boost::shared_ptr< ::lab_2::actionGoal > actionGoalPtr;
typedef boost::shared_ptr< ::lab_2::actionGoal const> actionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab_2::actionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab_2::actionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab_2::actionGoal_<ContainerAllocator1> & lhs, const ::lab_2::actionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab_2::actionGoal_<ContainerAllocator1> & lhs, const ::lab_2::actionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab_2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab_2::actionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab_2::actionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_2::actionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_2::actionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_2::actionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_2::actionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab_2::actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b8b3e2da8be658e01dee48451dead03";
  }

  static const char* value(const ::lab_2::actionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b8b3e2da8be658eULL;
  static const uint64_t static_value2 = 0x01dee48451dead03ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab_2::actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab_2/actionGoal";
  }

  static const char* value(const ::lab_2::actionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab_2::actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int64 request\n"
;
  }

  static const char* value(const ::lab_2::actionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab_2::actionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct actionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab_2::actionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab_2::actionGoal_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    Printer<int64_t>::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB_2_MESSAGE_ACTIONGOAL_H
