(cl:defpackage lab_1-srv
  (:use )
  (:export
   "ADDITION"
   "<ADDITION-REQUEST>"
   "ADDITION-REQUEST"
   "<ADDITION-RESPONSE>"
   "ADDITION-RESPONSE"
   "TURTLE_VELOCITY"
   "<TURTLE_VELOCITY-REQUEST>"
   "TURTLE_VELOCITY-REQUEST"
   "<TURTLE_VELOCITY-RESPONSE>"
   "TURTLE_VELOCITY-RESPONSE"
  ))

